#
enable-sync: true

world-to-track: "world"
# Discord Bot Token (NOTE: Replace with your own)
client-token: "who is rem, i love emilia"
# Discord Bot Prefix
bot-prefix: "mc!"
# What server the bot is bound to - NOTE: DO NOT CHANGE, AUTOMATICALLY SET BY THE BOT WHEN JOIN SERVER (CLEAR IT IF YOU WANT THE BOT ON A DIFFERENT SERVER)
bot-server-bind: ""
# What text channel the bot tracks - NOTE: DO NOT CHANGE, AUTOMATICALLY SET BY THE BOT WHEN USER RUNS `!bind` IN A TEXT CHANNEL
bot-channel-bind: ""
# Enables the "Verify" feature, tying a discord account to-
enable-verify: false
# The SQL Driver to use. Currently Supported is MySQL(mysql) and PostgreSQL(postgresql)
sql-driver: "postgresql"
# IP of Database, usually `[ip]:[port]`
sql-ip: "localhost:3306"
sql-database: "ServVerify"
sql-username: ""
sql-password: ""
server-sys: "[Server]: "
server-name: "l1npengtul's boomer server"
system-sys: "[System]: "

