# Enables bStats. Turning this off won't affect any functionality.
enable-bstats: true

# Enables the "Verify" feature, tying a discord account to an in game account
enable-verify: false

# Custom discord server link. If blank, the bot will generate one on the fly.
discord-server-link: ""
# Minecraft Server IP
minecraft-server-ip: ""
# Enable syncing between Discord <-> MC
enable-sync: true

# Discord Bot Token (NOTE: Replace with your own)
bot-token: "who is rem, i love emilia"
# Discord Bot Prefix
bot-prefix: "mc!"
# The bio text of the bot
bot-bio-text: "A link between worlds..."
# Playing... status of bot
bot-playing-status: "Vanguard of the Minecraft Server"

# Enable sync discord custom emojis
enable-emoji-sync: true

# Filter Player Join/Leave messages
filter-join-leave: false
# Filter In Game Notification (E.g. someone dies)
filter-ingame: false
# Filter Server Plugin Announcements (E.g. server shutdown)
filter_announcements: false

# What server broadcasts will be prefixed with. The space at the end is automatically appended.
server-message-prefix: "[Server]:"

# Channels for the bot, copy and paste desired channels here
# You may have multiple command channels.
bot-chat-sync-channel: 0
bot-command-channels:
  - 0
bot-logging-channel: 0
bot-server: 0

# Webhook ID to manage. Do not edit, managed by bot
webhook-url: 0

# A list of admin roles on the Discord Server. They can run history and moderation commands. By-ID
discord-admin-roles:
    - 0

# Enable chat filter
enable-literally-nineteen-eighty-four: false

# A chat filter. Case-insensitive, but won't work if you use capital letters.
# Does not sync to discord (will ignore uses of these words in discrd. get yourself a proper moderation bot)
# Every word **must** be less than 50 characters.
# NOTE: ***BAD*** THINGS HAPPEN IF FILTER IS ENABLED BUT `banned-words` IS EMPTY!
banned-words:
  - ""
# Message to send to the user when the chat filter is triggered in Minecraft
filtered-messageg: "§c§oSorry, but you are not allowed to say that as it violates our rules."

# Enables moderation features.
# Allow the bot to do moderation from Discord<->Minecraft and sync them up as well.
# Enables mute, kick/warn, ban
enable-bot-moderation-features: true

# The muted role ID to apply to a user when they are muted.
# This should be a long number, such as 741365968336322711
discord-muted-role: 0

# Delete number of days of messages
# Must be between 0-7. Defaults to zero.
discord-onban-delete-message-days: 0

# first time booting (does DB exist?)
# Do not edit
first-time: true

# Enables the Log4J mitigations. Recommended to keep on to protect dated clients.
enable-log4j-mitigations: true

# Log Kotlin Exposed SQL Queries
debug-log-sql: false

# Respect vanish (dont sync vanished players)
respect-vanish: true