name: "pengcord"
main: net.pengtul.pengcord.main.Main
version: 0.2.0
author: l1npengtul <l1npengtul@protonmail.com>
depend:
  - LuckPerms
  - Vault
  - ProtocolLib
softdepend: [ProtocolLib]
api-version: 1.18
description: Discord <-> Minecraft Verification and Sync Plugin
load: STARTUP
commands:
  verify:
    description: Verify Player
    usage: /verify <Discord Tag>
    permission: pengcord.verify.command
  unverify:
    description: Remove someone's verification. Player is automatically kicked. Permission is only needed if <player> is specified.
    usage: /unverify <player>
    permission: pengcord.verify.command
  whois:
    description: Look up someone by their Discord Username/Discord UUID/Minecraft Username/Minecraft UUID
    usage: /whois <player>
    permission: pengcord.command.whois
  me:
    description: Look up yourself.
    usage: /me
    permission: pengcord.command.me
  stopserver:
    description: Stop the Server
    usage: /stopserver <time seconds>
    permission: pengcord.command.stopserver
  info:
    description: Gets Server RAM usage and uptime
    usage: /info
    permission: pengcord.command.info
  pignore:
    description: Ignore a user (You won't see their Discord -> Minecraft sync anymore)
    usage: /pignore <user>
    permission: pengcord.command.ignore
  pignorelist:
    description: See a user's ignore list (empty for your own)
    usage: /pignore <user>
    permission: pengcord.command.ignore
  puignore:
    description: Unignore a user (You will see their Discord -> Minecraft sync again)
    usage: /puignore <user>
    permission: pengcord.command.ignore
  git:
    description: Gets link to development github
    usage: /git
    permission: pengcord.command.git
  reply:
    description: Replies to message synced from discord.
    usage: /reply <messageId> <content>
    permission: pengcord.command.reply
  warn:
    description: Warn a player. Will log the warn and also kick them from the server
    usage: /warn <player> <reason>
    permission: pengcord.punishments.warn
  mute:
    description: Mute a player. Time must be a <amt><unit> literal such as 10d or perm to ban permanently.
    usage: /mute <player> <reason> <time/perm>
    permission: pengcord.punishments.mute
  unmute:
    description: Unmute via a Mute ID. This can be obtained by using `/query m <player>`. Alternatively, pass in "all" for the first argument then a player for the second to pardon all their mutes.
    usage: /unmute <mute Id/all> <player?>
    permission: pengcord.punishments.unmute
  pban:
    description: Ban a player. Time must be a <amt><unit> literal such as 10d or perm to ban permanently.
    usage: /pban <player> <reason> <time/perm>
    permission: pengcord.punishments.ban
  punban:
    description: Pardon by a ban Id. This can be obtained by using `/query b <player>`. Alternatively, pass in "all" for the first argument then a player for the second to pardon all their bans.
    usage: /punban <ban Id/all> <player?>
    permission: pengcord.punishments.ban
  queryrecord:
    description: Query punishment history of a player. b -> Bans, m -> Mutes, w -> Warns, f -> Filter Alerts, a -> All
    usage: /queryrecord <b|m|w|f|a> <player>
    permission: pengcord.punishments.query
  querypunishment:
    description: Query a specific punishment. b -> Bans, m -> Mutes, w -> Warns, f -> Filter Alerts,
    usage: /querypunishment <b|m|w|f> <punishmentId>
    permission: pengcord.punishments.query

permissions:
  pengcord.verify:
    description: Everything related to the verify commands
    children:
      pengcord.verify.command:
        description: Allows the running of /verify, etc
        default: true
      pengcord.verify.undo:
        description: Allows the running of /unverify on others
        default: false
      pengcord.verify.undoself:
        description: Allows the running of /unverify on yourself
        default: true
  pengcord.command:
    description: All non-specialized in-game commands
    children:
      pengcord.command.stopserver:
        description: Allows running of /stopserver
        default: false
      pengcord.command.whois:
        description: Allows MC <-> Discord lookup
        default: true
      pengcord.command.info:
        description: Allows user to get server info
        default: true
      pengcord.command.me:
        description: Allows lookup of self.
        default: true
      pengcord.command.git:
        description: Allows search of github
        default: true
      pengcord.command.reply:
        description: Allows reply to synced messages
        default: true
  pengcord.punishments:
    description: All commands related to punishment. This is only useful if you enabled "enable-bot-moderation-features"
    children:
      pengcord.punishments.warn:
        description: Warn other players
        default: false
      pengcord.punishments.mute:
        description: Mute/Unmute other players
        default: false
      pengcord.punishments.ban:
        description: Ban/Unban other players
        default: false
      pengcord.punishments.query:
        description: Query the punishments of other players
        default: false
  pengcord.ignore:
    description: Commands related to /pignore
    children:
      pengcord.ignore.listothers:
        description: Query the ignorelist of other players
        default: false


