name: "pengcord"
main: net.pengtul.pengcord.main.Main
version: 0.0.1
depend:
  - LuckPerms
  - Vault
commands:
  verify:
    description: Verifies Players
    usage: /verify <Discord Tag>
    permission: pengcord.verify.command
  whoismc:
    description: Look up someone's discord ID by their username
    usage: /whoismc <player>
    permission: pengcord.command.whois
  whoisdisc:
    description: Look up someone's Minecraft from their Discord username + tag
    usage: /whoisdisc <discord tag>
    permission: pengcord.command.whois
  unverify:
    description: Remove someone's verification. Note that said user needs to relog for the changes to apply
    usage: /unverify <player>
    permission: pengcord.verify.undo
  stopserver:
    description: Stop the Server
    usage: /stopserver <time seconds>
    permission: pengcord.command.stopserver
  info:
    description: Gets Server RAM usage and uptime
    usage: /info
    permission: pengcord.command.info

permissions:
  pengcord.verify:
    description: Everything related to the verify commands
    children:
      pengcord.verify.command:
        description: Allows the running of /verify, etc
        default: true
      pengcord.verify.bypass:
        description: Allows these players to bypass the verification system
        default: false
      pengcord.verify.undo:
        description: Allows the running of /unverify
        default: false
  pengcord.command:
    description: All non-specialized in-game commands
    children:
      pengcord.command.stopserver:
        description: Allows running of /stopserver
        default: false
      pengcord.command.whois:
        description: Allows MC <-> Discord lookup
        default: true
      pengcord.command.info:
        description: Allows user to get server info
        default: true

